version: '1.0'

services:
  app:
    container_name: library-app
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: pnpm start:dev
    ports:
      - 3000:3000
    networks:
      - sharednet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    environment:
      PG_HOST: host.docker.internal
      MONGODB_USER_NAME:
      MONGODB_USER_PASSWORD:
      MONGODB_DATABASE_NAME:
      MONGODB_URL:
    depends_on:
      - postgres
      - mongodb
  postgres:
    container_name: library-postgres
    image: postgres:16.1
    networks:
      - sharednet
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/create-tables.sql:/docker-entrypoint-initdb.d/01_create-tables.sql
      - ./migrations/seed-data.sql:/docker-entrypoint-initdb.d/02_seed-data.sql
    ports:
      - 5432:5432
  mongodb:
    container_name: library-mongodb
    image: mongo
    networks:
      - sharednet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_USER_PASSWORD}
    ports:
      - 27017:27017
networks:
  sharednet:
volumes:
  pgdata:
